### PR TITLE
feat: format teams.csv

### PR DESCRIPTION
**Pull request by chesha1**
format teams.csv in lexicographic order, if the company name is in Chinese, format them in pinyin order

It is easier for contributors to find if there are missings or errors.

There is also a new workflow to check if new pr formats teams.csv

### CODE REVIEW

**Comment by LeslieLeung** [comment]
Thank you for your contribution.

I believe a basic `sort` command would suffice, refer to https://man7.org/linux/man-pages/man1/sort.1.html. This command has the potential to significantly streamline the process.

```bash
sort -t, -k2,2 -k1,1 teams.csv
```

Sorting Chinese pinyin should not pose an issue as long as the same algorithm is utilized, in case there are any concerns about biases.

**Comment by chesha1** [comment]
Thought `sort` can expectedly sort lines in lexicographic order in same algorithm, it is not user-friendly for Chinese contributors.

Directly using `sort`, they may have to use ctrl+f or scroll up and down to find certain company without pinyin order for Chinese words.

**Comment by LeslieLeung** [comment]
Alright. Some final styling issues to address before merging:

- Switch to using poetry for dependency management (install poetry and run `poetry add pypinyin`)
- Keep the script in the root directory, or if preferred, move it to a `script` folder
- Make sure to use English comments

**Comment by chesha1** [comment]
All things done.

Have you considered to create a new folder `docs` under repo root?

It is needed to clarify how to contribute to `teams.csv` and putting them in docs rather than in issue may be better as changes can be traced through git by then.

**Comment by LeslieLeung** [comment]
> All things done.
> 
> Have you considered to create a new folder `docs` under repo root?
> 
> It is needed to clarify how to contribute to `teams.csv` and putting them in docs rather than in issue may be better as changes can be traced through git by then.

That would be great. You can do that on a new PR as I am merging this one.

**Comment by LeslieLeung** [comment]
@chesha1 It seems you have forgotten to update the Actions configuration.

https://github.com/LeslieLeung/opensource-lighthouse/actions/runs/9761573684

**Comment by chesha1** [comment]
Fixed. You could approve the latest pending workflow to check if it works this time.

**Comment by LeslieLeung** [comment]
lgtm

**Pull request merged**
